### ISSUE TITLE
Scrapping Specific Language

### ISSUE THREAD

**Issue by 6wom9** [pdbenard/Web-Scrapping-Using-Snscrape-and-Sentiment-Analysis-of-ENDSARS-Tweet#1]
Hello,

Thanks for your sharing. It would be very helpful to understand the process of scrapping and analyzing the tweets.

I want to scrape tweets with a specific language. How do I do this modification? I tried to do something but I could not overcome it.

Thanks for your help in advance.

**Comment by pdbenard** [comment]
Hi,

Snscrape has a language query you can implement for scrapping specific languages.
![Attributes](https://user-images.githubusercontent.com/70017617/200190713-432dd886-c2e3-4830-af3b-61ae198a0558.png)

You can check out this link [https://stackoverflow.com/questions/72691870/how-to-scrape-twitter-tweets-of-a-specific-language-in-python](url)

I hope this helps.

**Comment by 6wom9** [comment]
Thanks for your reply.

`# Setting variables to be used below
maxTweets = 50
language=['en']

# Creating list to append tweet data to
tweets_list = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('fantoken').get_items()):
    
    if i>maxTweets:
        break
    if tweet.lang in language:
        tweets_list.append([tweet.date, tweet.id, tweet.content, tweet.lang, tweet.likeCount, tweet.replyCount, tweet.retweetCount, tweet.hashtags])`
I've modified the code as you see. However, something goes wrong. Crawled tweet amounts do not reach the amount of MaxTweets. I think I put wrong place the language section of the code.

I hope you can give me an advice.

**Comment by pdbenard** [comment]
Okay, you can specify the language as a part of the input parameters of the TwitterSearchScraper()
The link here should be helpful:
[https://github.com/JustAnotherArchivist/snscrape/issues/164]
